name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Building `potree` static files needs to be done first as they are used by `rust-embed`.
    - name: Build Potree JS
      run: make potree-build
    - name: Build Rust
      run: make build
    - name: Clippy
      run: make clippy
    - name: Run tests
      run: make test
